Implement sandboxing

diff --git a/hooks/bpapp b/hooks/bpapp
--- a/hooks/bpapp
+++ b/hooks/bpapp
@@ -1,13 +1,18 @@
 #!/usr/bin/bash
 
-TMPDIR=$(mktemp -d /tmp/webhook.homepage.XXXXXXXXXX) || exit 1
+if [ -z "$TMPDIR" ]; then
+  echo "TMPDIR not set or blank"
+  exit 1
+fi
+
 pushd "$TMPDIR" || exit 1
 git clone https://github.com/derdilla/blood-pressure-monitor-fl.git || exit  1
 
-docker run --rm -v "$TMPDIR/blood-pressure-monitor-fl:/repo" -v "$TMPDIR/output:/output" antonmedv/gitmal \
+docker run --rm -v "$TMPDIR/blood-pressure-monitor-fl:/repo" -v "$TMPDIR/output:/output" \
     -e GIT_CONFIG_COUNT=1 \
     -e GIT_CONFIG_KEY_0=safe.directory \
     -e GIT_CONFIG_VALUE_0=/repo \
+    antonmedv/gitmal \
     --minify \
     --output "/output" \
     --name "Blood Pressure Monitor" \
@@ -19,11 +24,10 @@ pushd "$TMPDIR/output" || exit 1
 find . -type f -regextype posix-extended -regex '.*\.(htm|html|css|js|xml|xsl|txt|woff|woff2|svg|otf|eot|ttf)' \
     -exec gzip --best -k -f {} \
     \+ -exec brotli --best -f {} \;
-popd || exit 2;
 
 # install
-rm -r /www/git.derdilla.com/bpapp
-cp -r public /www/git.derdilla.com/bpapp
+rm -r /www/git.derdilla.com/bpapp/*
+cp -r ./* /www/git.derdilla.com/bpapp/
+popd || exit 2
 
-# cleanup
-rm -r "$TMPDIR"
+# cleanup done by caller
diff --git a/hooks/homepage b/hooks/homepage
--- a/hooks/homepage
+++ b/hooks/homepage
@@ -1,14 +1,18 @@
 #!/usr/bin/bash
 
+if [ -z "$TMPDIR" ]; then
+  echo "TMPDIR not set or blank"
+  exit 1
+fi
+
 # download
-TMPDIR=$(mktemp -d /tmp/webhook.homepage.XXXXXXXXXX) || exit 1
 pushd "$TMPDIR" || exit 1
 curl -fLO https://github.com/derdilla/personal-website/archive/refs/heads/main.zip
 unzip main.zip
 
 # building
 pushd personal-website-main/ || exit 1
-docker run -u 0:0 -v /srv/derdilla.com/personal-website-main:/app --workdir /app ghcr.io/getzola/zola:v0.20.0 build || exit
+docker run -u 0:0 -v .:/app --workdir /app ghcr.io/getzola/zola:v0.20.0 build || exit
 
 pushd public || exit 1
 find . -type f -regextype posix-extended -regex '.*\.(htm|html|css|js|xml|xsl|txt|woff|woff2|svg|otf|eot|ttf)' \
@@ -19,5 +23,4 @@ popd || exit 2
 # install
 cp -r public/* /www/derdilla.com/
 
-# cleanup
-rm -rf "$TMPDIR"
+# cleanup done by caller
